// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7uZl-n5CfgIAscNAWUlx_SUBjB2jJVg',
    appId: '1:463492451643:web:510a334a7002c8b226bb1e',
    messagingSenderId: '463492451643',
    projectId: 'yoyo-b047d',
    authDomain: 'yoyo-b047d.firebaseapp.com',
    storageBucket: 'yoyo-b047d.firebasestorage.app',
    measurementId: 'G-1KGTZT1DH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWq5pVTZHL5PJa2GrSbDSPUZMffPhGQS8',
    appId: '1:463492451643:android:bea11ffce92d5fbf26bb1e',
    messagingSenderId: '463492451643',
    projectId: 'yoyo-b047d',
    storageBucket: 'yoyo-b047d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzUyLwTDuGsm5seK2XOfnlcktAxEDBNQc',
    appId: '1:463492451643:ios:ad6d8aff00d6d52826bb1e',
    messagingSenderId: '463492451643',
    projectId: 'yoyo-b047d',
    storageBucket: 'yoyo-b047d.firebasestorage.app',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzUyLwTDuGsm5seK2XOfnlcktAxEDBNQc',
    appId: '1:463492451643:ios:ad6d8aff00d6d52826bb1e',
    messagingSenderId: '463492451643',
    projectId: 'yoyo-b047d',
    storageBucket: 'yoyo-b047d.firebasestorage.app',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw7uZl-n5CfgIAscNAWUlx_SUBjB2jJVg',
    appId: '1:463492451643:web:9799ade8c91ee8a626bb1e',
    messagingSenderId: '463492451643',
    projectId: 'yoyo-b047d',
    authDomain: 'yoyo-b047d.firebaseapp.com',
    storageBucket: 'yoyo-b047d.firebasestorage.app',
    measurementId: 'G-FYCXPPW2J0',
  );

}